### ISSUE TITLE
Milestone 3 Expectations

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/covid-19-cases-vs-tests-analysis#55]
Link for Milestone3 in Canvas: https://canvas.ubc.ca/courses/59080/assignments/746041

- [x] You should be committing to git every time you work on this project. Thus, by the time you finish your final project, we expect to see 20+ commits in your git log. Make your commit messages meaningful!

- [x] This is an extension of Milestone 2, so keep working in the public repo you set up for that. You do however, still need to resubmit the URL to your project in your milestone3 repo's README.md file so we can easily find it when we're marking.

- [x] You should still have a well organized lab repo/directory structure.

- [x] The Makefile must be well documented. This means comments throughout, readable code and a brief summary at the top of each file that answers who wrote it, when it was written and what it does.

- [x] Your question, analysis and visualization should still make sense. Again, it doesn't have to be complicated, but you should tell a story and have a narrative. Specifically, this should come through in your README and Rmd file.

- [x] You should use proper grammar and full sentences in your README and report. Point form may occur, but should be less than 10% of your written documents.
- [x] Check dependencies under README - Usage. Make sure to add 'GNU make 4.2.1'

**Comment by tanmaysharma19** [comment]
Some of the expectations were deferred to Milestone 4 as per Tiffany's announcement.
