### ISSUE TITLE
Expectations for Milestone 1

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/covid-19-cases-vs-tests-analysis#8]
- [x] After the repository is set-up, each group member should fork the repository to their personal GitHub.com account and work there, and send pull-requests of their work to the upstream repo (the one they forked). The other team mate should review, critique (if necessary) and finally accept their team mates pull request.

- [x] You should be committing to git and pushing to GitHub.com every time you work on this project.

- [x] git commit messages should be meaningful. These will be marked. It's OK if one or two are less meaningful, but most should be.

- [x] Use GitHub issues to communicate to their team mate (as opposed to email or Slack)

- [x] Your question, analysis and visualization should make sense. It doesn't have to be complicated.

- [x] You should use proper grammar and full sentences in your README. Point form may occur, but should be less than 10% of your written documents.

- [x] You must include the URL of your public project's repository in your milestone 1 submission on Canvas, so we know where to find it.

- [x] Just before you submit the milestone 1, create a release on your project repository on GitHub and name it 0.0.1. Include the URL to this release in your milestone 1 submission on Canvas, so we can easily jump to the state of your repository at the time of submission for grading puroposes, while you continue to work on your project for the next milestone.

**Comment by tanmaysharma19** [comment]
Adding to the above, as discussed, the group will be maintaining a milestone checklist every week to track ownership and progress of individual work items. This list will also help ensure that all required tasks are completed prior to the submission deadline for each week.

The checklists can be found at: https://drive.google.com/drive/folders/1ZvLgVb186I8-LwL3qe9xxeH1UoIFyq6o?usp=sharing

**Comment by tanmaysharma19** [comment]
Reviewed with team during the morning meeting on Saturday, Nov 21.
